baseURL = 'https://fffzlfk.github.io'
languageCode = 'zh-cn'
title = "fffzlfk's Blog"
theme = ["paper", "hugo-notice"]
enableEmoji = true

# [services]
#   [services.disqus]
#     shortname = 'https-fffzlfk-github-io"'     # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'fffzlfk'                 # github.com/YOUR_GITHUB_ID
  instagram = 'fffzlfk'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  # bluesky = 'YOUR_BLUESKY_ID'               # https://bsky.app/profile/YOUR_BLUESKY_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/44939690?v=4'                 # gravatar email or image url
  name = 'fffzlfk'
  bio = 'Thinking will not overcome fear but action will.'


  # misc
  disableHLJS = true                       # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  # direction = "rtl"                         # RTL support for Right-to-left languages

  # giscus
[params.giscus]
  repo = 'fffzlfk/fffzlfk.github.io'                 # see https://giscus.app for more details
  repoId = 'R_kgDOG4ERGw'
  category = 'Q&A'
  categoryId = 'DIC_kwDOG4ERG84CBP5t'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'


[markup]
  [markup.highlight]
    style = 'monokai'
